#ifndef _WISELY_C3_AI_V2_CONFIG_H_
#define _WISELY_C3_AI_V2_CONFIG_H_

#include <driver/gpio.h>

// Audio: preserve the proven C3_AI_V2 pin map from the legacy firmware.
#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_10
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_12
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_8
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_7
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_11

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_13
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_0
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_1
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

// User I/O from C3_AI_V2.
#define BUILTIN_LED_GPIO          GPIO_NUM_20
#define BUILTIN_LED_OUTPUT_INVERT 0
#define BOOT_BUTTON_GPIO          GPIO_NUM_9
#define AUX_BUTTON_GPIO           GPIO_NUM_6

#endif  // _WISELY_C3_AI_V2_CONFIG_H_
