#!/usr/bin/env python3
"""Create a reproducible XiaoZhi firmware worktree with the Wisely C3 AI V2 overlay.

The upstream repository remains upstream-owned. This script clones a pinned stable
release, copies this project's board implementation into it, and applies the two
small build-system registrations required by XiaoZhi (Kconfig + CMake).
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION_FILE = ROOT / "UPSTREAM_VERSION"
BOARD_SOURCE = ROOT / "firmware" / "boards" / "wisely" / "c3-ai-v2"
DEFAULT_WORKDIR = ROOT / ".work" / "xiaozhi-esp32"
MARKER = ".wisely-c3-ai-v2-overlay.json"

KCONFIG_ANCHOR = '''    config BOARD_TYPE_KEVIN_C3
        bool "Kevin C3"
        depends on IDF_TARGET_ESP32C3'''
KCONFIG_INSERT = '''    config BOARD_TYPE_WISELY_C3_AI_V2
        bool "Wisely C3 AI V2"
        depends on IDF_TARGET_ESP32C3'''

CMAKE_ANCHOR = '''elseif(CONFIG_BOARD_TYPE_KEVIN_C3)
    set(BOARD_DIR "kevin/c3")'''
CMAKE_INSERT = '''elseif(CONFIG_BOARD_TYPE_WISELY_C3_AI_V2)
    set(BOARD_DIR "wisely/c3-ai-v2")'''


def run(command: list[str], *, cwd: Path | None = None) -> None:
    print("+", " ".join(command))
    subprocess.run(command, cwd=cwd, check=True)


def read_version_file() -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in VERSION_FILE.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        key, sep, value = line.partition("=")
        if not sep:
            raise ValueError(f"Invalid line in {VERSION_FILE}: {raw_line!r}")
        values[key.strip()] = value.strip()

    required = {"upstream_repo", "ref", "commit", "idf", "board", "name"}
    missing = sorted(required - values.keys())
    if missing:
        raise ValueError(f"Missing keys in {VERSION_FILE}: {', '.join(missing)}")
    return values


def insert_after_once(path: Path, anchor: str, insertion: str) -> None:
    text = path.read_text(encoding="utf-8")
    if insertion in text:
        return
    if anchor not in text:
        raise RuntimeError(
            f"Upstream layout changed: anchor not found in {path}. "
            "Review the new upstream release before updating UPSTREAM_VERSION."
        )
    path.write_text(text.replace(anchor, anchor + "\n" + insertion, 1), encoding="utf-8")


def prepare(workdir: Path, *, clean: bool) -> dict[str, str]:
    version = read_version_file()
    workdir = workdir.resolve()

    if clean and workdir.exists():
        print(f"Removing generated worktree: {workdir}")
        shutil.rmtree(workdir)

    if not workdir.exists():
        workdir.parent.mkdir(parents=True, exist_ok=True)
        run([
            "git", "clone", "--depth", "1", "--branch", version["ref"],
            version["upstream_repo"], str(workdir),
        ])
    else:
        marker_path = workdir / MARKER
        if not marker_path.exists():
            raise RuntimeError(
                f"{workdir} already exists but was not generated by this project. "
                "Choose another --workdir or pass --clean."
            )
        marker = json.loads(marker_path.read_text(encoding="utf-8"))
        if marker.get("ref") != version["ref"] or marker.get("commit") != version["commit"]:
            raise RuntimeError(
                "Generated worktree uses a different upstream revision. "
                "Run again with --clean."
            )

    actual_commit = subprocess.check_output(
        ["git", "rev-parse", "HEAD"], cwd=workdir, text=True
    ).strip()
    if actual_commit != version["commit"]:
        raise RuntimeError(
            f"Pinned ref mismatch: expected {version['commit']}, got {actual_commit}. "
            "Do not build until UPSTREAM_VERSION is reviewed."
        )

    board_target = workdir / "main" / "boards" / "wisely" / "c3-ai-v2"
    board_target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(BOARD_SOURCE, board_target, dirs_exist_ok=True)

    insert_after_once(workdir / "main" / "Kconfig.projbuild", KCONFIG_ANCHOR, KCONFIG_INSERT)
    insert_after_once(workdir / "main" / "CMakeLists.txt", CMAKE_ANCHOR, CMAKE_INSERT)

    marker = {
        "source": version["upstream_repo"],
        "ref": version["ref"],
        "commit": version["commit"],
        "idf": version["idf"],
        "board": version["board"],
        "name": version["name"],
    }
    (workdir / MARKER).write_text(
        json.dumps(marker, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    print("\nPrepared firmware worktree successfully.")
    print(f"Worktree: {workdir}")
    print(f"Upstream: {version['ref']} @ {version['commit']}")
    print(f"ESP-IDF:  {version['idf']}")
    print("Build:")
    print(
        f"  cd {workdir} && python scripts/build.py {version['board']} "
        f"--name {version['name']} --language zh-CN --wake-word nihaoxiaozhi --zip"
    )
    return version


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--workdir", type=Path, default=DEFAULT_WORKDIR,
        help=f"Generated upstream worktree (default: {DEFAULT_WORKDIR})",
    )
    parser.add_argument(
        "--clean", action="store_true",
        help="Delete and recreate the generated worktree before applying the overlay.",
    )
    args = parser.parse_args()

    try:
        prepare(args.workdir, clean=args.clean)
    except (OSError, ValueError, RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
